# Generated by Django 5.0.6 on 2024-06-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro_store', '0003_rename_image_url_car_image_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='image_url',
        ),
    ]
